'''
Rosalind Problems: [MRNA] Inferring mRNA from Protein
'''

def mrna(protein):
	codon_table = { 'UUU': 'F', 'CUU': 'L', 'AUU': 'I', 'GUU': 'V', \
					'UUC': 'F', 'CUC': 'L', 'AUC': 'I', 'GUC': 'V', \
					'UUA': 'L', 'CUA': 'L', 'AUA': 'I', 'GUA': 'V', \
					'UUG': 'L', 'CUG': 'L', 'AUG': 'M', 'GUG': 'V', \
					'UCU': 'S', 'CCU': 'P', 'ACU': 'T', 'GCU': 'A', \
					'UCC': 'S', 'CCC': 'P', 'ACC': 'T', 'GCC': 'A', \
					'UCA': 'S', 'CCA': 'P', 'ACA': 'T', 'GCA': 'A', \
					'UCG': 'S', 'CCG': 'P', 'ACG': 'T', 'GCG': 'A', \
					'UAU': 'Y', 'CAU': 'H', 'AAU': 'N', 'GAU': 'D', \
					'UAC': 'Y', 'CAC': 'H', 'AAC': 'N', 'GAC': 'D', \
					'UAA': 'Stop', 'CAA': 'Q', 'AAA': 'K', 'GAA': 'E', \
					'UAG': 'Stop', 'CAG': 'Q', 'AAG': 'K', 'GAG': 'E', \
					'UGU': 'C', 'CGU': 'R', 'AGU': 'S', 'GGU': 'G', \
					'UGC': 'C', 'CGC': 'R', 'AGC': 'S', 'GGC': 'G', \
					'UGA': 'Stop', 'CGA': 'R', 'AGA': 'R', 'GGA': 'G', \
					'UGG': 'W', 'CGG': 'R', 'AGG': 'R', 'GGG': 'G'}
	rna_num = 0
	for a in codon_table.values():
		if a == 'Stop':
			rna_num += 1
	for i in protein:
		pn = 0
		for j in codon_table.values():
			if j == i:
				pn +=1
		rna_num = rna_num * pn % 1000000
	return rna_num

pro = 'MTNYGLGYKYEDRSWHHTGEWKDWECFQCKMFAQMFKHSTFFWCFSLPGLWKEYNPPPMDGAIRTHAVQAGRGQCIVHSLTMPLRTMEYVAHHDNCERKQGIGIMEHTVPQMHWSLECNKMNWNWFPSFLTWDSIGPIEDYGQPPVQYVGIPHRDKQFWGVQYCCVAALIYNFKAWKIGQNTAPLDYDDQCGSDANFKMLWPFIHLPSWKKGSVMIMVICKQEVLDNVSHQKTTPGTENGTHCVYACQMMWIMQNQENKDSPDIIEGSNSVDGVWYLHTNCTYLWPKHRMVWQVWDMCKQESDWHGEKHECATWQLKQWFDQFMRRVTPIMLDNVEGWWNSHSQHHLVMSFERWWRYTGVSYVTYKYWGMISYTYQVFWDFHRNWGRSPQAGEEHEEPDPNMWPQKWGFICQHAWFSVDDLEVQLHATGSCHAAISYGHHMYKCRTMCSNTEGKDHNHDHTVVQDWSHDVTWCPDHQDCTNRQSRNCWEKFSVDDEMRYYDEGDKMFTPHFDCHWQQACWCSIGCFSKRKQGQSKVWLFCNTTEWKMAHSDYYQEADDFMWTNIGQKNYHKNSSAFLDVLQGQMKYHWTGWVNSCATTIYQHRLELYEHEIHKGEYHVEGCYWLLQRATWRRDEHMCYTWSIVVATHNDQIPAVPLWDELDASYENAFVQSNPLNEKGWFKFSLSVNYGMRGFVCANSCHKMFKNGESHQWRKGYNRWLIHFTPWTLHRQGVHQFKPVATIQHETNPKLLMWCNYLERIERWHDDNVKNWLRDHGWLKQDRVFPQPEAYHCGAQEPLGQNGIPSYVDMDQGHFQEGCSTVYMDMQHDWELCNHGTPVFPTICYCADWFDCRNRTIKAVPIPPLGKDIKNEIYMIEAWVWVTPPRAKAGRPKHYLQTDDDPCHDGWECDLYILHKVDYDIWKVNWTGQCFGAMERSSILHWCDQPIQDWMQNSVFTNGSRQLYAYWKCHFSYKSNPVQVKLCQCWVILAMEKHYWIHMT'

print(mrna(pro))