'''
Rosalind Problems: [SUBS] Finding a Motif in DNA
'''

def locate_motif(dnaseq, sub):
	sub_len = len(sub)
	dna_len = len(dnaseq)
	frame = dna_len - sub_len +1
	location = []
	for i in range(frame):
		if dnaseq[i:i+sub_len] == sub:
			location.append(i+1)
	return location

dna = 'CTGTCAGCCTGTCAGTCGCCTTTGACTGTCAGCCTGTCAGGCTGTCAGACTGTCAGTCAGCTGTCAGGACCTGTCAGATCTGTCAGCATTTTCTGTCAGGGGAATCCCCTGTCAGGTGGGTTCTGTCAGACCAACCTGTCAGGTGCTGTCAGTACTGTCAGCTGTCAGCTCTGTCAGTATCATGCGCTGTCAGCTGTCAGCTGTCAGCTGTCAGTCTGTCAGCACTGTCAGACTGTCAGACTCAGCTGTCAGGAATTACTACTGTCAGCGGTCGTGCCTGTCAGCCAGACTGTCAGGCTGTCAGCTGTCAGCTGTCAGCAACTGTCAGTGGGGCCCCGCTGTCAGCGCGCTGTCAGGATCTGTCAGGGTTGCTGTCAGCTGTCAGCTGTCAGTCCTTTTTAGACTGTCAGACCTGTCAGCCTGTCAGCGCCCAGGTCTGTCAGGCTGTCAGCAGGGTGTGAACTGTCAGCCTGTCAGACCTGTCAGACCCTGTCAGCTGTCAGCTGTCAGCCGCCTGTCAGCGTCCCTGGCCTGTCAGGGCCCTCTGTCAGCTGTCAGGCCTGTCAGACTGTCAGGGATCGCCTGTCAGCTGTCAGACTGTCAGCTGTCAGCCTGTCAGGTTTGACTGTCAGCTGTCAGAAACTGTCAGACTGTCAGTCTGTCAGCTCTGTCAGCTGTCAGGCTGTCAGCAACTGTCAGGCTACTGTCAGCTGTCAGGCGGCACTGTCAGGCTGTCAGCTGTCAGCTGTCAGGTCACTGTCAGTCTGTCAGGACTGTCAGCTGTCAGATGGCTGTCAGCATACTGTCAGACCTGTCAG'
substring = 'CTGTCAGCT'

location_list = locate_motif(dna,substring)
for i in location_list:
	print(i, end=' ')